#ifndef _MY_GLOBAL
#define _MY_GLOBAL 

extern Literal minus, left, sin, cos, ln, ctg, arcsin, arccos, arctg, arcctg, sh, ch, exp, spare, number, x, tg, end, plus, mul, divis, deg, right;
extern Literal S, E, T, F, K, G;
// extern Literal left;
// extern Literal sin;
// extern Literal cos;
// extern Literal ln;
// extern Literal ctg;
// extern Literal arcsin;
// extern Literal arccos;
// extern Literal arctg;
// extern Literal arcctg;
// extern Literal sh;
// extern Literal ch;
// extern Literal exp;
// extern Literal spare;
// extern Literal number;
// extern Literal x;
// extern Literal tg;
// extern Literal end;
// extern Literal plus;
// extern Literal mul;
// extern Literal divis;
// extern Literal deg;
// extern Literal right;
// extern Literal S;
// extern Literal E;
// extern Literal T;
// extern Literal F;
// extern Literal K;
// extern Literal G;
extern Literal right0[1];
extern Literal right1[3];
extern Literal right2[3];
extern Literal right3[1];
extern Literal right4[3];
extern Literal right5[3];
extern Literal right6[1];
extern Literal right7[3];
extern Literal right8[1];
extern Literal right9[2];
extern Literal right10[1];
extern Literal right11[3];
extern Literal right12[4];
extern Literal right13[4];
extern Literal right14[4];
extern Literal right15[4];
extern Literal right16[4];
extern Literal right17[4];
extern Literal right18[4];
extern Literal right19[4];
extern Literal right20[4];
extern Literal right21[4];
extern Literal right22[4];
extern Literal right23[4];
extern Literal right24[4];
extern Literal right25[1];
extern Literal right26[1];

extern Rule rule0;
extern Rule rule1;
extern Rule rule2;
extern Rule rule3;
extern Rule rule4;
extern Rule rule5;
extern Rule rule6;
extern Rule rule7;
extern Rule rule8;
extern Rule rule9;
extern Rule rule10;
extern Rule rule11;
extern Rule rule12;
extern Rule rule13;
extern Rule rule14;
extern Rule rule15;
extern Rule rule16;
extern Rule rule17;
extern Rule rule18;
extern Rule rule19;
extern Rule rule20;
extern Rule rule21;
extern Rule rule22;
extern Rule rule23;
extern Rule rule24;
extern Rule rule25;
extern Rule rule26;

#endif
